import React from "react";
import {
  X,
  Brain,
  Sparkles,
  Clock,
} from "lucide-react";

const ExplainHeader = ({ title, onClose }) => {
  const currentTime = new Date().toLocaleString();

  return (
    <div className="border-b border-slate-200 bg-gradient-to-r from-slate-50 via-white to-slate-50 px-8 py-6">

      <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

        {/* Left */}

        <div className="flex items-center gap-5">

          <div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-blue-100 shadow-sm">

            <Brain
              size={32}
              className="text-blue-600"
            />

          </div>

          <div>

            <div className="flex items-center gap-2">

              <h2 className="text-3xl font-bold text-slate-800">
                {title}
              </h2>

              <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold uppercase tracking-wide text-blue-700">
                AI
              </span>

            </div>

            <p className="mt-2 text-slate-500">
              Intelligent explanation generated by CreditWise AI
            </p>

          </div>

        </div>

        {/* Right */}

        <div className="flex items-center gap-4">

          <div className="hidden rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm md:flex md:items-center md:gap-3">

            <Clock
              size={18}
              className="text-slate-500"
            />

            <div>

              <p className="text-xs uppercase tracking-wide text-slate-400">
                Generated
              </p>

              <p className="text-sm font-semibold text-slate-700">
                {currentTime}
              </p>

            </div>

          </div>

          <div className="hidden rounded-2xl bg-indigo-100 px-4 py-3 md:flex md:items-center md:gap-2">

            <Sparkles
              size={18}
              className="text-indigo-600"
            />

            <span className="text-sm font-semibold text-indigo-700">
              Explainable AI
            </span>

          </div>

          <button
            onClick={onClose}
            className="flex h-12 w-12 items-center justify-center rounded-2xl border border-slate-200 bg-white text-slate-600 transition-all duration-200 hover:bg-red-50 hover:text-red-600 hover:shadow-md"
          >

            <X size={22} />

          </button>

        </div>

      </div>

    </div>
  );
};

export default ExplainHeader;