import React from "react";
import {
  CheckCircle2,
  ShieldCheck,
  AlertTriangle,
  ClipboardCheck,
  Lightbulb,
} from "lucide-react";

const RecommendationCard = ({ prediction }) => {
  const probability = prediction?.probability_default || 0;
  const percent = Math.round(probability * 100);

  const recommendation =
    percent >= 70
      ? {
          title: "Decline Credit",
          color: "text-red-600",
          bg: "bg-red-50",
          border: "border-red-200",
          icon: <AlertTriangle size={24} />,
          actions: [
            "Avoid immediate credit approval.",
            "Request additional financial verification.",
            "Review repayment history manually.",
          ],
        }
      : percent >= 40
      ? {
          title: "Manual Review",
          color: "text-yellow-600",
          bg: "bg-yellow-50",
          border: "border-yellow-200",
          icon: <ShieldCheck size={24} />,
          actions: [
            "Perform manual underwriting.",
            "Verify income and liabilities.",
            "Consider reduced credit limit.",
          ],
        }
      : {
          title: "Approve Credit",
          color: "text-green-600",
          bg: "bg-green-50",
          border: "border-green-200",
          icon: <CheckCircle2 size={24} />,
          actions: [
            "Eligible for approval.",
            "Continue regular monitoring.",
            "Maintain standard repayment checks.",
          ],
        };

  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

      {/* Header */}

      <div className="flex items-center gap-4">

        <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-100">

          <ClipboardCheck
            size={28}
            className="text-indigo-600"
          />

        </div>

        <div>

          <h3 className="text-2xl font-bold text-slate-800">
            Decision Recommendation
          </h3>

          <p className="mt-1 text-slate-500">
            AI-assisted recommendation based on the prediction outcome.
          </p>

        </div>

      </div>

      {/* Decision Card */}

      <div
        className={`mt-8 rounded-2xl border p-6 ${recommendation.bg} ${recommendation.border}`}
      >

        <div className="flex items-center gap-4">

          <div className={recommendation.color}>
            {recommendation.icon}
          </div>

          <div>

            <h4 className={`text-2xl font-bold ${recommendation.color}`}>
              {recommendation.title}
            </h4>

            <p className="mt-2 text-slate-600">
              Default Probability: <strong>{percent}%</strong>
            </p>

          </div>

        </div>

      </div>

      {/* Recommended Actions */}

      <div className="mt-8">

        <div className="mb-5 flex items-center gap-3">

          <Lightbulb
            size={22}
            className="text-amber-500"
          />

          <h4 className="text-lg font-bold text-slate-800">
            Recommended Actions
          </h4>

        </div>

        <div className="space-y-4">

          {recommendation.actions.map((action, index) => (

            <div
              key={index}
              className="flex items-start gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"
            >

              <CheckCircle2
                size={20}
                className="mt-0.5 text-green-600"
              />

              <span className="leading-7 text-slate-700">
                {action}
              </span>

            </div>

          ))}

        </div>

      </div>

      {/* Disclaimer */}

      <div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50 p-5">

        <h4 className="font-semibold text-blue-700">
          Decision Support
        </h4>

        <p className="mt-2 text-sm leading-7 text-slate-600">

          This recommendation is generated by the CreditWise AI model.
          It should support—not replace—human decision-making. Consider
          additional customer information, institutional policies, and
          regulatory requirements before making a final lending decision.

        </p>

      </div>

    </section>
  );
};

export default RecommendationCard;