import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function exportBatchPDF(results = []) {
  if (!results.length) return;

  const doc = new jsPDF();

  // ===== Title =====
  doc.setFontSize(20);
  doc.setTextColor(30, 41, 59);
  doc.text("CreditWise AI", 14, 18);

  doc.setFontSize(15);
  doc.setTextColor(75, 85, 99);
  doc.text("Batch Prediction Report", 14, 28);

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    36
  );

  // ===== Statistics =====

  const high = results.filter((r) => r.risk === "High").length;
  const medium = results.filter((r) => r.risk === "Medium").length;
  const low = results.filter((r) => r.risk === "Low").length;

  const defaults = results.filter(
    (r) => r.prediction === 1
  ).length;

  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  doc.text(`Total Customers : ${results.length}`, 14, 48);
  doc.text(`High Risk       : ${high}`, 14, 55);
  doc.text(`Medium Risk     : ${medium}`, 14, 62);
  doc.text(`Low Risk        : ${low}`, 14, 69);
  doc.text(`Predicted Default : ${defaults}`, 14, 76);

  // ===== Table =====

  const rows = results.map((row, index) => [
    index + 1,
    Number(row.LIMIT_BAL).toLocaleString("en-IN"),
    row.AGE,
    `${Number(row.probability_default || 0).toFixed(2)}%`,
    row.prediction === 1 ? "Default" : "Safe",
    row.risk,
  ]);

  autoTable(doc, {
    startY: 86,

    head: [[
      "ID",
      "Credit Limit",
      "Age",
      "Probability",
      "Prediction",
      "Risk",
    ]],

    body: rows,

    theme: "striped",

    headStyles: {
      fillColor: [37, 99, 235],
      halign: "center",
    },

    bodyStyles: {
      halign: "center",
    },

    styles: {
      fontSize: 9,
    },
  });

  // ===== Footer =====

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(9);
  doc.setTextColor(140);

  doc.text(
    "Generated by CreditWise AI",
    14,
    pageHeight - 10
  );

  doc.save("CreditWise_Batch_Report.pdf");
}