import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const PRIMARY = [37, 99, 235];
const SUCCESS = [34, 197, 94];
const WARNING = [245, 158, 11];
const DANGER = [239, 68, 68];
const DARK = [30, 41, 59];

function formatDate() {
  return new Date().toLocaleString();
}

function getRisk(probability) {
  const percent = Math.round(probability * 100);

  if (percent >= 70)
    return {
      label: "HIGH RISK",
      color: DANGER,
    };

  if (percent >= 40)
    return {
      label: "MEDIUM RISK",
      color: WARNING,
    };

  return {
    label: "LOW RISK",
    color: SUCCESS,
  };
}

function drawHeader(doc) {
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("CreditWise AI", 14, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(
    "AI Powered Credit Risk Assessment Platform",
    14,
    24
  );
}

function drawFooter(doc) {
  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setDrawColor(220);
    doc.line(15, 287, 195, 287);

    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      `Generated by CreditWise AI`,
      15,
      293
    );

    doc.text(
      `Page ${i} of ${pages}`,
      180,
      293
    );
  }
}

function customerTable(doc, prediction) {
  autoTable(doc, {
    startY: 42,

    head: [["Customer Information", "Value"]],

    body: [
      [
        "Customer ID",
        prediction.id ?? "N/A",
      ],
      [
        "Credit Limit",
        `₹${Number(
          prediction.limit_bal ?? 0
        ).toLocaleString()}`,
      ],
      [
        "Age",
        prediction.age ?? "-",
      ],
      [
        "Education",
        prediction.education ?? "-",
      ],
      [
        "Prediction Time",
        formatDate(),
      ],
    ],

    headStyles: {
      fillColor: PRIMARY,
    },

    styles: {
      fontSize: 10,
    },
  });
}

export function generatePDF(prediction) {

  const doc = new jsPDF();

  drawHeader(doc);

  customerTable(doc, prediction);

  const risk = getRisk(
    prediction.probability_default || 0
  );

  const percent = Math.round(
    (prediction.probability_default || 0) * 100
  );

  doc.setFontSize(18);
  doc.setTextColor(...DARK);

  doc.text(
    "Risk Assessment",
    14,
    108
  );

  doc.setFillColor(...risk.color);

  doc.roundedRect(
    14,
    116,
    182,
    24,
    4,
    4,
    "F"
  );

  doc.setTextColor(255);

  doc.setFontSize(22);

  doc.text(
    `${risk.label} (${percent}%)`,
    20,
    132
  );  // ----------------------------
  // AI SUMMARY
  // ----------------------------

  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("AI Assessment Summary", 14, 155);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summary =
    prediction.summary ||
    "No AI-generated summary available for this prediction.";

  const wrappedSummary = doc.splitTextToSize(summary, 178);

  doc.roundedRect(14, 160, 182, 28, 3, 3);
  doc.text(wrappedSummary, 18, 168);

  // ----------------------------
  // FEATURE IMPORTANCE
  // ----------------------------

  let startY = 200;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...DARK);
  doc.text("Top Influencing Features", 14, startY);

  const features = prediction.top_features || [];

  autoTable(doc, {
    startY: startY + 6,

    head: [["Feature", "Impact"]],

    body:
      features.length > 0
        ? features.map((item) => [
            item.feature || "-",
            item.impact || item.value || "-"
          ])
        : [["No feature data available", "-"]],

    headStyles: {
      fillColor: PRIMARY
    },

    styles: {
      fontSize: 10
    }
  });

  // ----------------------------
  // RECOMMENDATIONS
  // ----------------------------

  const nextY = doc.lastAutoTable.finalY + 15;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Recommendations", 14, nextY);

  const recommendations =
    percent >= 70
      ? [
          "Review customer's repayment history.",
          "Reduce lending exposure.",
          "Request additional financial verification.",
          "Monitor payment behaviour closely."
        ]
      : percent >= 40
      ? [
          "Approve with caution.",
          "Recommend moderate credit limit.",
          "Schedule periodic reviews."
        ]
      : [
          "Eligible for normal approval.",
          "Standard monitoring is sufficient.",
          "Customer demonstrates healthy repayment behaviour."
        ];

  autoTable(doc, {
    startY: nextY + 6,

    head: [["#", "Recommendation"]],

    body: recommendations.map((r, i) => [
      i + 1,
      r
    ]),

    headStyles: {
      fillColor: PRIMARY
    },

    styles: {
      fontSize: 10
    }
  });  // ----------------------------
  // MODEL INFORMATION
  // ----------------------------

  let infoY = doc.lastAutoTable.finalY + 15;

  // If we're near the bottom of the page, create a new page
  if (infoY > 235) {
    doc.addPage();
    infoY = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...DARK);
  doc.text("Model Information", 14, infoY);

  autoTable(doc, {
    startY: infoY + 6,

    head: [["Property", "Value"]],

    body: [
      ["Model", prediction.model_name || "Random Forest"],
      ["Version", prediction.model_version || "1.0.0"],
      [
        "Prediction",
        prediction.prediction === 1
          ? "Likely Default"
          : "Likely No Default"
      ],
      [
        "Probability of Default",
        `${Math.round(
          (prediction.probability_default || 0) * 100
        )}%`
      ],
      [
        "Probability of No Default",
        `${Math.round(
          (prediction.probability_no_default || 0) * 100
        )}%`
      ],
      ["Generated On", formatDate()]
    ],

    headStyles: {
      fillColor: PRIMARY
    },

    styles: {
      fontSize: 10
    }
  });

  // ----------------------------
  // REPORT DISCLAIMER
  // ----------------------------

  const disclaimerY = doc.lastAutoTable.finalY + 15;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...DARK);
  doc.text("Disclaimer", 14, disclaimerY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const disclaimer = doc.splitTextToSize(
    "This report was generated automatically by CreditWise AI. "
    + "Predictions are based on the machine learning model and the "
    + "information provided during analysis. This report is intended "
    + "to support decision-making and should not be treated as the "
    + "sole basis for financial approval or rejection.",
    178
  );

  doc.text(disclaimer, 14, disclaimerY + 8);

  // ----------------------------
  // FOOTER
  // ----------------------------

  drawFooter(doc);

  // ----------------------------
  // SAVE PDF
  // ----------------------------

  const fileName = `CreditWise_Report_${
    prediction.id || Date.now()
  }.pdf`;

  doc.save(fileName);
}
